/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewRouteImport } from './routes/new'
import { Route as ApiExtractRouteImport } from './routes/api/extract'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as TomeCampaignIdRouteImport } from './routes/tome.$campaignId'
import { Route as TomeCampaignIdIndexRouteImport } from './routes/tome.$campaignId.index'
import { Route as TomeCampaignIdPartyRouteImport } from './routes/tome.$campaignId.party'
import { Route as TomeCampaignIdPlacesRouteImport } from './routes/tome.$campaignId.places'
import { Route as TomeCampaignIdRecordRouteImport } from './routes/tome.$campaignId.record'
import { Route as TomeCampaignIdPartyIndexRouteImport } from './routes/tome.$campaignId.party.index'
import { Route as TomeCampaignIdPartyCharacterIdRouteImport } from './routes/tome.$campaignId.party.$characterId'
import { Route as TomeCampaignIdPlacesIndexRouteImport } from './routes/tome.$campaignId.places.index'
import { Route as TomeCampaignIdPlacesLocationIdRouteImport } from './routes/tome.$campaignId.places.$locationId'
import { Route as TomeCampaignIdSessionSessionIdRouteImport } from './routes/tome.$campaignId.session.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractRoute = ApiExtractRouteImport.update({
  id: '/api/extract',
  path: '/api/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TomeCampaignIdRoute = TomeCampaignIdRouteImport.update({
  id: '/tome/$campaignId',
  path: '/tome/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const TomeCampaignIdIndexRoute = TomeCampaignIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TomeCampaignIdRoute,
} as any)
const TomeCampaignIdPartyRoute = TomeCampaignIdPartyRouteImport.update({
  id: '/party',
  path: '/party',
  getParentRoute: () => TomeCampaignIdRoute,
} as any)
const TomeCampaignIdPlacesRoute = TomeCampaignIdPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => TomeCampaignIdRoute,
} as any)
const TomeCampaignIdRecordRoute = TomeCampaignIdRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => TomeCampaignIdRoute,
} as any)
const TomeCampaignIdPartyIndexRoute =
  TomeCampaignIdPartyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TomeCampaignIdPartyRoute,
  } as any)
const TomeCampaignIdPartyCharacterIdRoute =
  TomeCampaignIdPartyCharacterIdRouteImport.update({
    id: '/$characterId',
    path: '/$characterId',
    getParentRoute: () => TomeCampaignIdPartyRoute,
  } as any)
const TomeCampaignIdPlacesIndexRoute =
  TomeCampaignIdPlacesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TomeCampaignIdPlacesRoute,
  } as any)
const TomeCampaignIdPlacesLocationIdRoute =
  TomeCampaignIdPlacesLocationIdRouteImport.update({
    id: '/$locationId',
    path: '/$locationId',
    getParentRoute: () => TomeCampaignIdPlacesRoute,
  } as any)
const TomeCampaignIdSessionSessionIdRoute =
  TomeCampaignIdSessionSessionIdRouteImport.update({
    id: '/session/$sessionId',
    path: '/session/$sessionId',
    getParentRoute: () => TomeCampaignIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/tome/$campaignId': typeof TomeCampaignIdRouteWithChildren
  '/tome/$campaignId/party': typeof TomeCampaignIdPartyRouteWithChildren
  '/tome/$campaignId/places': typeof TomeCampaignIdPlacesRouteWithChildren
  '/tome/$campaignId/record': typeof TomeCampaignIdRecordRoute
  '/tome/$campaignId/': typeof TomeCampaignIdIndexRoute
  '/tome/$campaignId/party/$characterId': typeof TomeCampaignIdPartyCharacterIdRoute
  '/tome/$campaignId/places/$locationId': typeof TomeCampaignIdPlacesLocationIdRoute
  '/tome/$campaignId/session/$sessionId': typeof TomeCampaignIdSessionSessionIdRoute
  '/tome/$campaignId/party/': typeof TomeCampaignIdPartyIndexRoute
  '/tome/$campaignId/places/': typeof TomeCampaignIdPlacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/tome/$campaignId/record': typeof TomeCampaignIdRecordRoute
  '/tome/$campaignId': typeof TomeCampaignIdIndexRoute
  '/tome/$campaignId/party/$characterId': typeof TomeCampaignIdPartyCharacterIdRoute
  '/tome/$campaignId/places/$locationId': typeof TomeCampaignIdPlacesLocationIdRoute
  '/tome/$campaignId/session/$sessionId': typeof TomeCampaignIdSessionSessionIdRoute
  '/tome/$campaignId/party': typeof TomeCampaignIdPartyIndexRoute
  '/tome/$campaignId/places': typeof TomeCampaignIdPlacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/tome/$campaignId': typeof TomeCampaignIdRouteWithChildren
  '/tome/$campaignId/party': typeof TomeCampaignIdPartyRouteWithChildren
  '/tome/$campaignId/places': typeof TomeCampaignIdPlacesRouteWithChildren
  '/tome/$campaignId/record': typeof TomeCampaignIdRecordRoute
  '/tome/$campaignId/': typeof TomeCampaignIdIndexRoute
  '/tome/$campaignId/party/$characterId': typeof TomeCampaignIdPartyCharacterIdRoute
  '/tome/$campaignId/places/$locationId': typeof TomeCampaignIdPlacesLocationIdRoute
  '/tome/$campaignId/session/$sessionId': typeof TomeCampaignIdSessionSessionIdRoute
  '/tome/$campaignId/party/': typeof TomeCampaignIdPartyIndexRoute
  '/tome/$campaignId/places/': typeof TomeCampaignIdPlacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/api/extract'
    | '/api/transcribe'
    | '/tome/$campaignId'
    | '/tome/$campaignId/party'
    | '/tome/$campaignId/places'
    | '/tome/$campaignId/record'
    | '/tome/$campaignId/'
    | '/tome/$campaignId/party/$characterId'
    | '/tome/$campaignId/places/$locationId'
    | '/tome/$campaignId/session/$sessionId'
    | '/tome/$campaignId/party/'
    | '/tome/$campaignId/places/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/api/extract'
    | '/api/transcribe'
    | '/tome/$campaignId/record'
    | '/tome/$campaignId'
    | '/tome/$campaignId/party/$characterId'
    | '/tome/$campaignId/places/$locationId'
    | '/tome/$campaignId/session/$sessionId'
    | '/tome/$campaignId/party'
    | '/tome/$campaignId/places'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/api/extract'
    | '/api/transcribe'
    | '/tome/$campaignId'
    | '/tome/$campaignId/party'
    | '/tome/$campaignId/places'
    | '/tome/$campaignId/record'
    | '/tome/$campaignId/'
    | '/tome/$campaignId/party/$characterId'
    | '/tome/$campaignId/places/$locationId'
    | '/tome/$campaignId/session/$sessionId'
    | '/tome/$campaignId/party/'
    | '/tome/$campaignId/places/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  ApiExtractRoute: typeof ApiExtractRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  TomeCampaignIdRoute: typeof TomeCampaignIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract': {
      id: '/api/extract'
      path: '/api/extract'
      fullPath: '/api/extract'
      preLoaderRoute: typeof ApiExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tome/$campaignId': {
      id: '/tome/$campaignId'
      path: '/tome/$campaignId'
      fullPath: '/tome/$campaignId'
      preLoaderRoute: typeof TomeCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tome/$campaignId/': {
      id: '/tome/$campaignId/'
      path: '/'
      fullPath: '/tome/$campaignId/'
      preLoaderRoute: typeof TomeCampaignIdIndexRouteImport
      parentRoute: typeof TomeCampaignIdRoute
    }
    '/tome/$campaignId/party': {
      id: '/tome/$campaignId/party'
      path: '/party'
      fullPath: '/tome/$campaignId/party'
      preLoaderRoute: typeof TomeCampaignIdPartyRouteImport
      parentRoute: typeof TomeCampaignIdRoute
    }
    '/tome/$campaignId/places': {
      id: '/tome/$campaignId/places'
      path: '/places'
      fullPath: '/tome/$campaignId/places'
      preLoaderRoute: typeof TomeCampaignIdPlacesRouteImport
      parentRoute: typeof TomeCampaignIdRoute
    }
    '/tome/$campaignId/record': {
      id: '/tome/$campaignId/record'
      path: '/record'
      fullPath: '/tome/$campaignId/record'
      preLoaderRoute: typeof TomeCampaignIdRecordRouteImport
      parentRoute: typeof TomeCampaignIdRoute
    }
    '/tome/$campaignId/party/': {
      id: '/tome/$campaignId/party/'
      path: '/'
      fullPath: '/tome/$campaignId/party/'
      preLoaderRoute: typeof TomeCampaignIdPartyIndexRouteImport
      parentRoute: typeof TomeCampaignIdPartyRoute
    }
    '/tome/$campaignId/party/$characterId': {
      id: '/tome/$campaignId/party/$characterId'
      path: '/$characterId'
      fullPath: '/tome/$campaignId/party/$characterId'
      preLoaderRoute: typeof TomeCampaignIdPartyCharacterIdRouteImport
      parentRoute: typeof TomeCampaignIdPartyRoute
    }
    '/tome/$campaignId/places/': {
      id: '/tome/$campaignId/places/'
      path: '/'
      fullPath: '/tome/$campaignId/places/'
      preLoaderRoute: typeof TomeCampaignIdPlacesIndexRouteImport
      parentRoute: typeof TomeCampaignIdPlacesRoute
    }
    '/tome/$campaignId/places/$locationId': {
      id: '/tome/$campaignId/places/$locationId'
      path: '/$locationId'
      fullPath: '/tome/$campaignId/places/$locationId'
      preLoaderRoute: typeof TomeCampaignIdPlacesLocationIdRouteImport
      parentRoute: typeof TomeCampaignIdPlacesRoute
    }
    '/tome/$campaignId/session/$sessionId': {
      id: '/tome/$campaignId/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/tome/$campaignId/session/$sessionId'
      preLoaderRoute: typeof TomeCampaignIdSessionSessionIdRouteImport
      parentRoute: typeof TomeCampaignIdRoute
    }
  }
}

interface TomeCampaignIdPartyRouteChildren {
  TomeCampaignIdPartyCharacterIdRoute: typeof TomeCampaignIdPartyCharacterIdRoute
  TomeCampaignIdPartyIndexRoute: typeof TomeCampaignIdPartyIndexRoute
}

const TomeCampaignIdPartyRouteChildren: TomeCampaignIdPartyRouteChildren = {
  TomeCampaignIdPartyCharacterIdRoute: TomeCampaignIdPartyCharacterIdRoute,
  TomeCampaignIdPartyIndexRoute: TomeCampaignIdPartyIndexRoute,
}

const TomeCampaignIdPartyRouteWithChildren =
  TomeCampaignIdPartyRoute._addFileChildren(TomeCampaignIdPartyRouteChildren)

interface TomeCampaignIdPlacesRouteChildren {
  TomeCampaignIdPlacesLocationIdRoute: typeof TomeCampaignIdPlacesLocationIdRoute
  TomeCampaignIdPlacesIndexRoute: typeof TomeCampaignIdPlacesIndexRoute
}

const TomeCampaignIdPlacesRouteChildren: TomeCampaignIdPlacesRouteChildren = {
  TomeCampaignIdPlacesLocationIdRoute: TomeCampaignIdPlacesLocationIdRoute,
  TomeCampaignIdPlacesIndexRoute: TomeCampaignIdPlacesIndexRoute,
}

const TomeCampaignIdPlacesRouteWithChildren =
  TomeCampaignIdPlacesRoute._addFileChildren(TomeCampaignIdPlacesRouteChildren)

interface TomeCampaignIdRouteChildren {
  TomeCampaignIdPartyRoute: typeof TomeCampaignIdPartyRouteWithChildren
  TomeCampaignIdPlacesRoute: typeof TomeCampaignIdPlacesRouteWithChildren
  TomeCampaignIdRecordRoute: typeof TomeCampaignIdRecordRoute
  TomeCampaignIdIndexRoute: typeof TomeCampaignIdIndexRoute
  TomeCampaignIdSessionSessionIdRoute: typeof TomeCampaignIdSessionSessionIdRoute
}

const TomeCampaignIdRouteChildren: TomeCampaignIdRouteChildren = {
  TomeCampaignIdPartyRoute: TomeCampaignIdPartyRouteWithChildren,
  TomeCampaignIdPlacesRoute: TomeCampaignIdPlacesRouteWithChildren,
  TomeCampaignIdRecordRoute: TomeCampaignIdRecordRoute,
  TomeCampaignIdIndexRoute: TomeCampaignIdIndexRoute,
  TomeCampaignIdSessionSessionIdRoute: TomeCampaignIdSessionSessionIdRoute,
}

const TomeCampaignIdRouteWithChildren = TomeCampaignIdRoute._addFileChildren(
  TomeCampaignIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  ApiExtractRoute: ApiExtractRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  TomeCampaignIdRoute: TomeCampaignIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
